name: Dewhurst Security Blog
meta_description: "Dewhurst Security Blog"
baseurl: http://blog.dewhurstsecurity.com

markdown: redcarpet
highlighter: pygments
paginate: 15
excerpt_separator: https://github.com/jekyll/jekyll/issues/1401